### ISSUE TITLE
MockUps ertsellen

### ISSUE THREAD

**Issue by sophiareinke** [KirstenLob/DemenzKalenderApp#9]
MockUps erstellen für: 

- [x]  Registrierung 
- [x] Login
- [x] Hauptseite - Sicht PA (Fragebogen Funktionalitäten)
- [x] Eigenes Profil
- [x] Profil der zu betreuenden Person 
- [x] Termin hinzufügen - Button (Fragebogen)
- [x] Person hinzufügen - Button
- [x] Person löschen - Button 
- [x] Ansicht Kalender (2 Varianten für die Fragebögen)
- [x] Wochentags-Ansicht 
- [x] Jahresansicht 
- [x] Monatsansicht 
- [x] Termin - Ansicht

**Comment by KirstenLob** [comment]
Sieht super aus :)
Gute Arbeit😁
